# Generated by Django 6.0 on 2025-12-23 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('nice_to_have', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Internship')], default='FULL_TIME', max_length=20)),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('JUNIOR', 'Junior'), ('MID', 'Mid Level'), ('SENIOR', 'Senior'), ('LEAD', 'Lead'), ('MANAGER', 'Manager'), ('DIRECTOR', 'Director'), ('EXECUTIVE', 'Executive')], default='MID', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('remote_policy', models.CharField(choices=[('REMOTE', 'Fully Remote'), ('HYBRID', 'Hybrid'), ('ONSITE', 'On-site')], default='ONSITE', max_length=20)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_period', models.CharField(choices=[('HOURLY', 'Hourly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='YEARLY', max_length=20)),
                ('parsed_skills', models.JSONField(blank=True, default=list)),
                ('parsed_requirements', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(unique=True)),
                ('source_platform', models.CharField(blank=True, max_length=100)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('FILLED', 'Filled'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('application_count', models.IntegerField(default=0)),
                ('is_scraped', models.BooleanField(default=False)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_added', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('MUST_HAVE', 'Must Have'), ('NICE_TO_HAVE', 'Nice to Have'), ('PREFERRED', 'Preferred')], default='MUST_HAVE', max_length=20)),
                ('minimum_proficiency', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('years_required', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_requirements', to='profiles.skill')),
            ],
            options={
                'verbose_name': 'Job Skill Requirement',
                'verbose_name_plural': 'Job Skill Requirements',
                'db_table': 'job_skill_requirements',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(related_name='jobs_required', through='jobs.JobSkillRequirement', to='profiles.skill'),
        ),
        migrations.CreateModel(
            name='JobEligibilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_context', models.TextField(blank=True, help_text='Additional context provided by user')),
                ('eligibility_level', models.CharField(choices=[('EXCELLENT', 'Excellent Match'), ('GOOD', 'Good Match'), ('FAIR', 'Fair Match'), ('POOR', 'Poor Match')], max_length=20)),
                ('match_score', models.IntegerField(help_text='Overall match score (0-100)')),
                ('analysis_summary', models.TextField(help_text='Overall summary of eligibility analysis')),
                ('strengths', models.JSONField(default=list, help_text="User's strengths for this job")),
                ('gaps', models.JSONField(default=list, help_text='Skill/experience gaps identified')),
                ('recommendations', models.JSONField(default=list, help_text='Recommendations for improving candidacy')),
                ('matching_skills', models.JSONField(default=list, help_text='Skills that match job requirements')),
                ('missing_skills', models.JSONField(default=list, help_text="Required skills user doesn't have")),
                ('skill_gaps', models.JSONField(default=list, help_text='Detailed skill gap analysis with severity and priority')),
                ('skills_match_score', models.IntegerField(default=0, help_text="How well user's skills match job requirements (0-100)")),
                ('experience_match_score', models.IntegerField(default=0, help_text="How well user's experience matches job requirements (0-100)")),
                ('education_match_score', models.IntegerField(default=0, help_text="How well user's education matches job requirements (0-100)")),
                ('culture_fit_score', models.IntegerField(default=0, help_text='Estimated culture/values fit score (0-100)')),
                ('location_match_score', models.IntegerField(default=0, help_text='Location/remote preference match score (0-100)')),
                ('salary_match_score', models.IntegerField(default=0, help_text='Salary expectation vs offering match score (0-100)')),
                ('technical_skills_score', models.IntegerField(default=0, help_text='Technical skills match (0-100)')),
                ('soft_skills_score', models.IntegerField(default=0, help_text='Soft skills match (0-100)')),
                ('domain_knowledge_score', models.IntegerField(default=0, help_text='Domain/industry knowledge match (0-100)')),
                ('experience_match', models.TextField(blank=True, help_text="How user's experience matches job requirements")),
                ('experience_gap_years', models.DecimalField(blank=True, decimal_places=1, help_text='Years of experience gap (if any)', max_digits=4, null=True)),
                ('years_of_experience_required', models.DecimalField(blank=True, decimal_places=1, help_text='Years of experience required by job', max_digits=4, null=True)),
                ('years_of_experience_user', models.DecimalField(blank=True, decimal_places=1, help_text='Years of experience user has', max_digits=4, null=True)),
                ('readiness_percentage', models.IntegerField(default=0, help_text='Overall readiness percentage (0-100)')),
                ('estimated_preparation_time', models.CharField(blank=True, help_text='Estimated time to become job-ready', max_length=100)),
                ('confidence_level', models.CharField(choices=[('VERY_HIGH', 'Very High'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('VERY_LOW', 'Very Low')], default='MEDIUM', help_text='Confidence level for this match', max_length=20)),
                ('next_steps', models.JSONField(default=list, help_text='Concrete next steps to improve candidacy')),
                ('priority_improvements', models.JSONField(default=list, help_text='Top 3-5 priority improvements ranked by impact')),
                ('learning_resources', models.JSONField(default=list, help_text='Recommended courses, certifications, or resources')),
                ('full_analysis', models.TextField(help_text='Complete AI-generated analysis')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('llm_model', models.CharField(default='gpt-4', help_text='LLM model used for analysis', max_length=100)),
                ('token_usage', models.IntegerField(default=0, help_text='Tokens used for this analysis')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_analyses', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Eligibility Analysis',
                'verbose_name_plural': 'Job Eligibility Analyses',
                'db_table': 'job_eligibility_analyses',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['user', '-analyzed_at'], name='job_eligibi_user_id_b0f7aa_idx'), models.Index(fields=['job', '-analyzed_at'], name='job_eligibi_job_id_4194e4_idx'), models.Index(fields=['eligibility_level'], name='job_eligibi_eligibi_454a1c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title', 'company_name'], name='jobs_title_ea0fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-created_at'], name='jobs_status_70b954_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_level'], name='jobs_experie_96c339_idx'),
        ),
    ]
